/* Generated By:JJTree: Do not edit this line. C:/workspaces/rdp_080/workspace/SQLJEP/src/org/medfoster/sqljep\ParserVisitor.java */

package org.medfoster.sqljep;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws ParseException;
  public Object visit(ASTStart node, Object data) throws ParseException;
  public Object visit(ASTFunNode node, Object data) throws ParseException;
  public Object visit(ASTVarNode node, Object data) throws ParseException;
  public Object visit(ASTArray node, Object data) throws ParseException;
  public Object visit(ASTConstant node, Object data) throws ParseException;
}
