/* Generated By:JJTree: Do not edit this line. ASTStart.java */
package org.medfoster.sqljep;

import org.medfoster.sqljep.exceptions.ParseException;

/**
 * Start Node
 */
public class ASTStart extends SimpleNode {
    public ASTStart(int id) {
        super(id);
    }

    public ASTStart(Parser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    @Override
    public Object jjtAccept(ParserVisitor visitor, Object data) throws ParseException {
        return visitor.visit(this, data);
    }
}
