/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.medfoster.sqljep;

public interface ParserConstants {

  int EOF = 0;
  int MULTI_LINE_COMMENT = 5;
  int CONCAT = 6;
  int PLUS = 7;
  int MINUS = 8;
  int MUL = 9;
  int DIV = 10;
  int MOD = 11;
  int GT = 12;
  int LT = 13;
  int EQ = 14;
  int LE = 15;
  int GE = 16;
  int NE = 17;
  int NE_2 = 18;
  int AND = 19;
  int OR = 20;
  int NOT = 21;
  int IS_NULL = 22;
  int IS_NOT_NULL = 23;
  int IN = 24;
  int BETWEEN = 25;
  int NOT_BETWEEN = 26;
  int LIKE = 27;
  int NOT_LIKE = 28;
  int NULL_LITERAL = 29;
  int TRUE_LITERAL = 30;
  int FALSE_LITERAL = 31;
  int INTEGER_LITERAL = 32;
  int DECIMAL_LITERAL = 33;
  int FLOATING_POINT_LITERAL = 34;
  int EXPONENT = 35;
  int STRING_LITERAL = 36;
  int IDENTIFIER = 37;
  int LETTER = 38;
  int DIGIT = 39;
  int OTHER_LETTER = 40;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<MULTI_LINE_COMMENT>",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"mod\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<>\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"is null\"",
    "\"is not null\"",
    "\"in\"",
    "\"between\"",
    "\"not between\"",
    "\"like\"",
    "\"not like\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<OTHER_LETTER>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
